// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeV1OWySwybjppRaP9dk4pPh55IZBZsoM',
    appId: '1:806811639009:web:228bbcf1a18a5997ceaba0',
    messagingSenderId: '806811639009',
    projectId: 'busha-2024',
    authDomain: 'busha-2024.firebaseapp.com',
    storageBucket: 'busha-2024.appspot.com',
    measurementId: 'G-Q24K6EEMJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZkbrjSz_Ybj6Fuc8mu71cv8BnilzFWVA',
    appId: '1:806811639009:android:df093562dedc8741ceaba0',
    messagingSenderId: '806811639009',
    projectId: 'busha-2024',
    storageBucket: 'busha-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa9tGm0hT4gkkXs8z4qqRGUB96bo2UyAI',
    appId: '1:806811639009:ios:63af0c73db4ea673ceaba0',
    messagingSenderId: '806811639009',
    projectId: 'busha-2024',
    storageBucket: 'busha-2024.appspot.com',
    iosBundleId: 'com.example.compFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa9tGm0hT4gkkXs8z4qqRGUB96bo2UyAI',
    appId: '1:806811639009:ios:49a829532f560ca9ceaba0',
    messagingSenderId: '806811639009',
    projectId: 'busha-2024',
    storageBucket: 'busha-2024.appspot.com',
    iosBundleId: 'com.example.compFlutter.RunnerTests',
  );
}
